version: '3.1'
services:
  stats-server:
    build: stat-service/server
    image: docker_stat
    container_name: docker_stat
    ports:
      - "9090:9090"
    depends_on:
          - stats-db
    environment:
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stat


  stats-db:
    image: postgres:14-alpine
    container_name: ewm_postgres_stat
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5434/ewm_main
      - CLIENT_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_postgres_main
    ports:
      - "6543:5434"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
